sudo: required
services:
  - docker

before_install:
  - docker build -t mir23cr/docker-react -f Dockerfile.dev .

script:
  - docker run mir23cr/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react" 
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-393275633865"
  bucket_path: "docker-react" # Use the same name of your app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"